import './style.css'

const items = [
  ['THALI','Thali #1'],['THALI','Thali #2'],['THALI','Thali #3'],['THALI','Thali #4'],
  ['WAZWAN','Basmati Rice'],['WAZWAN','Rista'],['WAZWAN','Kebab'],['WAZWAN','Rogan Josh'],['WAZWAN','Daniwal Korma'],['WAZWAN','Aab Gosh'],['WAZWAN','Tabakmaaz'],['WAZWAN','Dayyin'],['WAZWAN','Mirchi Korma'],['WAZWAN','Tang'],['WAZWAN','Methi Maaz'],['WAZWAN','Shami Kebab'],['WAZWAN','Goshtaab'],['WAZWAN','Goshtab (Small)'],['WAZWAN','Lahbi Kebab'],['WAZWAN','Waza Chicken'],['WAZWAN','White Chicken'],
  ['TANDOORI','Tandoori Chicken'],['TANDOORI','Tandoori Momos'],['TANDOORI','Afghani Chicken'],
  ['INDIAN','Butter Chicken (Boneless)'],['INDIAN','Butter Chicken (With Bone)'],['INDIAN','Chicken Kadhai'],['INDIAN','Masala Chicken'],['INDIAN','Chicken Curry'],['INDIAN','Mutton Kadhai'],['INDIAN','Mutton Keema'],["INDIAN","Deekay's Special Butter Chicken"],['INDIAN','Mutter Mushroom'],['INDIAN','Butter Paneer'],['INDIAN','Mutter Paneer'],['INDIAN','Chicken Kanti (With Bone)'],['INDIAN','Chicken Kanti (Boneless)'],['INDIAN','Kebab Kanti'],['INDIAN','Rista Kanti'],['INDIAN','Mutton Kanti'],['INDIAN','Shahi Paneer'],['INDIAN','Shahi Chicken (Boneless)'],['INDIAN','Shahi Chicken (With Bone)'],
  ['PIZZA',"Dee Kay's Special Pizza"],['PIZZA','Chicken Blast'],['PIZZA','Butter Chicken Pizza'],['PIZZA','Chilli Chicken Pizza'],['PIZZA','Chicken Manchurian Pizza'],['PIZZA','Mushroom Pizza'],['PIZZA','Extra Cheese Pizza'],['PIZZA','Sweet Corn Pizza'],['PIZZA','Baby Corn Pizza'],['PIZZA','Tandoori Pizza'],['PIZZA','Mutton Pizza'],['PIZZA','Veg Pizza'],['PIZZA','Mexican Bite'],
  ['CHINESE','Chilli Chicken'],['CHINESE','Lemon Chicken'],['CHINESE','Chicken Fried Rice'],['CHINESE','Mutton Fried Rice'],['CHINESE','Egg Fried Rice'],['CHINESE','Veg Fried Rice'],['CHINESE','Jeera Rice'],['CHINESE','Steamed Momos'],['CHINESE','Fried Momos'],
  ['BIRYANI',"Dee Kay's Special Biryani"],['BIRYANI','Wazwan Biryani'],['BIRYANI','Chicken Biryani'],['BIRYANI','Signature Biryani'],['BIRYANI','Mutton Biryani'],['BIRYANI','Biryani Rice Extra'],['BIRYANI','Wazwan Biryani Premium'],
  ['KFC','Crispy Chicken (5 PC)'],['KFC','Crispy Chicken (10 PC)'],['KFC','Crispy Chicken (20 PC)'],['KFC','Chicken Popcorn'],['KFC','Crispy Momos'],['KIDS CHOICE','Veg Chowmein'],['KIDS CHOICE','Chicken Chowmein'],['KIDS CHOICE','Plain Maggi'],['KIDS CHOICE','Chicken Blast Regular Pizza'],['KIDS CHOICE','Extra Cheese Regular Pizza'],['PULAO','Kashmiri Dum Pulao'],['PULAO','Mutton Pulao'],['PULAO','Veg Pulao'],['PULAO','Chicken Pulao'],['ROTI / NAAN','Plain Naan'],['ROTI / NAAN','Butter Naan'],['ROTI / NAAN','Onion Kulcha Naan'],['ROTI / NAAN','Garlic Naan'],['ROTI / NAAN','Plain Roti'],['ROTI / NAAN','Butter Roti'],['DESSERTS','Shahi Kheer'],['DESSERTS','Ice Cream'],['DESSERTS','Fruit Custard (4 Bowls)'],['SALAD','Green Salad'],['SALAD',"Dee Kay's Special Salad"],['WINTER SPECIAL','Harissa / KG'],['WINTER SPECIAL','Harissa Plate'],['SHAKES','Date Shake'],['SHAKES','Mango Shake'],['SHAKES','Orange Shake'],['SHAKES','Strawberry Shake'],['SHAKES','Banana Shake'],['SHAKES','Oreo Shake'],['SHAKES','Chocolate Shake'],['SHAKES','KitKat Shake'],['SHAKES','Vanilla Milkshake'],['SHAKES',"Dee Kay's Special Shake"],['BEVERAGES','Fresh Lemon Soda'],['BEVERAGES','Green Apple'],['BEVERAGES','Blueberry'],['BEVERAGES','Watermelon'],['BEVERAGES','Strawberry Blush'],['BEVERAGES','Mojito Mint'],['BEVERAGES','Virgin Mojito'],['COFFEE / TEA','Plain Coffee'],['COFFEE / TEA','Classic Coffee'],['COFFEE / TEA','Black Coffee'],['COFFEE / TEA','Cold Coffee'],['COFFEE / TEA','Cappuccino'],['COFFEE / TEA','Hot Chocolate'],['COFFEE / TEA','Tea With Milk'],['COFFEE / TEA','Lemon Tea'],['COFFEE / TEA','Kashmiri Kehwa']
].map(([category,name])=>({category,name}))
const groups = [
  {title:'Kashmiri table', kicker:'01 — 02', cats:['THALI','WAZWAN','BIRYANI','PULAO'], style:'heritage'},
  {title:'From the tandoor', kicker:'03 — 04', cats:['TANDOORI','INDIAN'], style:'editorial'},
  {title:'City favourites', kicker:'05 — 06', cats:['PIZZA','CHINESE','KFC','KIDS CHOICE'], style:'urban'},
  {title:'The café counter', kicker:'07 — 08', cats:['SHAKES','BEVERAGES','COFFEE / TEA'], style:'cafe'},
  {title:'At the table', kicker:'09 — 10', cats:['ROTI / NAAN','DESSERTS','SALAD','WINTER SPECIAL'], style:'dining'}
]
const app = document.querySelector('#app')
app.innerHTML = `
<div class="grain"></div><header><a class="wordmark" href="#top">DEE KAY'S <i>RESTRO & CAFE</i></a><nav><a href="#about">About</a><a href="#menu">Menu</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></nav><button class="button small open-menu">VIEW MENU <b>↗</b></button></header>
<main id="top"><section class="hero"><div class="hero-copy"><p class="eyebrow">SOPŌRE · KASHMIR</p><h1>GOOD FOOD.<br><em>GOOD MOMENTS.</em></h1><p class="lede">A memorable dining experience in Sopore, Kashmir.</p><div class="hero-actions"><button class="button open-menu">OPEN THE MENU <b>↗</b></button><a class="text-link" href="#contact">GET DIRECTIONS <span>↓</span></a></div></div><div class="stage" id="stage"><button class="search-launch" aria-label="Search menu">SEARCH MENU <span>⌕</span></button><div class="book" id="book" tabindex="0" aria-label="Interactive Dee Kay's menu"><div class="book-edge"></div><div class="cover"><span class="cover-corner">SOPŌRE · KASHMIR</span><div class="cover-mark">DK</div><h2>DEE<br>KAY'S</h2><p>RESTRO & CAFE</p><div class="cover-line"></div><small>GOOD FOOD · GOOD MOMENTS</small></div></div><p class="drag-hint">DRAG TO EXPLORE <span>↔</span></p></div><div class="scroll-note">SCROLL TO DISCOVER <span></span></div></section>
<section id="about" class="about section"><p class="eyebrow">AN OPEN TABLE</p><h2>A TASTE OF<br><em>DEE KAY'S.</em></h2><p>From the Kashmiri Wazwan table to Indian favourites, Chinese plates, pizza, biryani, fast food, shakes, beverages, coffee, tea and desserts — the menu travels widely while staying rooted in Sopore.</p><div class="about-rule"></div><div class="about-tags"><span>WAZWAN</span><span>INDIAN</span><span>CHINESE</span><span>PIZZA</span><span>CAFÉ</span></div></section>
<section id="menu" class="menu-section section"><div class="section-head"><div><p class="eyebrow">THE DIGITAL BOOK</p><h2>EXPLORE THE<br><em>MENU.</em></h2></div><button class="button search-launch">SEARCH MENU <b>⌕</b></button></div><div class="category-bar">${[...new Set(items.map(x=>x.category))].map(c=>`<button data-cat="${c}">${c}</button>`).join('')}</div><div class="menu-book"><div class="menu-page" id="menuPage"></div><div class="menu-controls"><button id="prev">← PREVIOUS</button><span id="pageCount">01 / 05</span><button id="next">NEXT →</button></div></div></section>
<section class="flavours section"><p class="eyebrow">KASHMIR, ON THE MENU</p><h2>THE FLAVOURS<br>OF <em>KASHMIR.</em></h2><div class="flavour-list"><span>RISTA</span><span>ROGAN JOSH</span><span>TABAKMAAZ</span><span>GOSHTAAB</span><span>WAZWAN BIRYANI</span><span>KASHMIRI DUM PULAO</span><span>KASHMIRI KEHWA</span><span>HARISSA</span></div></section>
<section id="gallery" class="gallery section"><div><p class="eyebrow">IMAGE ARCHIVE</p><h2>THE TABLE,<br><em>AS YOU SEE IT.</em></h2><p>Space reserved for Dee Kay's own photography. Replace these panels with restaurant images whenever they are ready.</p></div><div class="gallery-grid">${['WAZWAN','INDIAN','PIZZA','CHINESE','BIRYANI','DESSERTS','BEVERAGES','RESTAURANT'].map((x,i)=>`<article class="placeholder p${i}"><span>DEE KAY'S / ${x}</span><strong>${x}</strong><small>PHOTO PLACEHOLDER</small></article>`).join('')}</div></section>
<section id="contact" class="contact"><div class="contact-copy"><p class="eyebrow">FIND THE TABLE</p><h2>DEE KAY'S<br><em>RESTRO & CAFE.</em></h2><address>Shaban Complex<br>Fruit Mandi Road<br>Near Dar Bazar<br>Nowpora Kalan<br>Sopore<br>Jammu & Kashmir 193201</address><div class="hero-actions"><a class="button" target="_blank" href="https://www.google.com/maps/search/?api=1&query=Shaban+Complex+Fruit+Mandi+Road+Near+Dar+Bazar+Nowpora+Kalan+Sopore">GET DIRECTIONS <b>↗</b></a><span class="call-note">Contact details are not published here.</span></div></div><div class="map"><iframe title="Map showing Dee Kay's area in Sopore" src="https://www.google.com/maps?q=Nowpora%20Kalan%20Sopore&output=embed" loading="lazy"></iframe></div></section>
</main><footer><div class="wordmark">DEE KAY'S <i>RESTRO & CAFE</i></div><p>Sopore, Kashmir</p><div><a href="#top">HOME</a><a href="#about">ABOUT</a><a href="#menu">MENU</a><a href="#gallery">GALLERY</a><a href="#contact">CONTACT</a></div><small>© 2026 Dee Kay's Resto & Cafe<br>All rights reserved.</small></footer>
<button class="float-menu" id="navTrigger">MENU <span>+</span></button><dialog id="search"><button class="close" aria-label="Close search">×</button><p class="eyebrow">SEARCH THE MENU</p><input id="searchInput" autofocus placeholder="Search dishes, drinks & categories..." /><div id="results"></div></dialog><dialog id="navigator"><button class="close" aria-label="Close menu navigation">×</button><p class="eyebrow">JUMP TO A CATEGORY</p><div class="nav-cats">${[...new Set(items.map(x=>x.category))].map(c=>`<button data-cat="${c}">${c}<span>→</span></button>`).join('')}</div></dialog>`

let page = 0
const pageEl = document.querySelector('#menuPage'), count = document.querySelector('#pageCount')
function renderPage(){ const g=groups[page]; const dishes=items.filter(x=>g.cats.includes(x.category)); pageEl.className='menu-page '+g.style; pageEl.innerHTML=`<div class="page-ornament">✦</div><p class="eyebrow">${g.kicker}</p><h3>${g.title}</h3><div class="menu-columns">${g.cats.map(cat=>`<section><h4>${cat}</h4>${dishes.filter(x=>x.category===cat).map(d=>`<button class="dish" data-name="${d.name}"><span>${d.name}</span><i>VIEW</i></button>`).join('')}</section>`).join('')}</div>`; count.textContent=`${String(page+1).padStart(2,'0')} / ${String(groups.length).padStart(2,'0')}` }
renderPage()
document.querySelector('#next').onclick=()=>{page=(page+1)%groups.length;renderPage()}; document.querySelector('#prev').onclick=()=>{page=(page+groups.length-1)%groups.length;renderPage()}
function toCategory(cat){page=groups.findIndex(g=>g.cats.includes(cat));renderPage();document.querySelector('#menu').scrollIntoView({behavior:'smooth'});document.querySelector('#navigator').close()}
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>toCategory(b.dataset.cat))
document.querySelectorAll('.open-menu').forEach(b=>b.onclick=()=>{document.querySelector('#menu').scrollIntoView({behavior:'smooth'});document.querySelector('#book').classList.add('opened')})
const search=document.querySelector('#search'), input=document.querySelector('#searchInput'), results=document.querySelector('#results')
document.querySelectorAll('.search-launch').forEach(b=>b.onclick=()=>{search.showModal();input.value='';renderResults(items.slice(0,8));setTimeout(()=>input.focus(),100)})
function renderResults(list){results.innerHTML=list.length?list.map(x=>`<button class="result" data-cat="${x.category}"><span>${x.name}</span><small>${x.category}</small><b>VIEW →</b></button>`).join(''):'<p class="none">No matching dishes found.</p>';results.querySelectorAll('button').forEach(b=>b.onclick=()=>{search.close();toCategory(b.dataset.cat)})} input.oninput=()=>{let q=input.value.toLowerCase();renderResults(items.filter(x=>(x.name+x.category).toLowerCase().includes(q)).slice(0,30))}; document.querySelectorAll('.close').forEach(x=>x.onclick=()=>x.closest('dialog').close()); document.querySelector('#navTrigger').onclick=()=>document.querySelector('#navigator').showModal()
let drag=false,sx=0,rx=0;const book=document.querySelector('#book');book.addEventListener('pointerdown',e=>{drag=true;sx=e.clientX;book.setPointerCapture(e.pointerId)});book.addEventListener('pointermove',e=>{if(drag){rx+=(e.clientX-sx)*.35;sx=e.clientX;book.style.setProperty('--rx',rx+'deg')}});book.addEventListener('pointerup',()=>drag=false);book.addEventListener('dblclick',()=>book.classList.toggle('opened'))
